using Technology_Market_Management_System.Classes;

namespace Blackhole.Forms
{
    public partial class Test : DevExpress.XtraEditors.XtraForm
    {
        private Computers computers = new Computers();
        public Test()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource asynchronously

        }
        private void tileBar_SelectedItemChanged(object sender, TileItemEventArgs e)
        {

        }

        private void Test_Load(object sender, EventArgs e)
        {
            bunifuCustomDataGrid2.DataSource = computers.GetShortImage();

        }

        private void fillToolStripButton_Click(object sender, EventArgs e)
        {


        }

        private void gridControl1_Click(object sender, EventArgs e)
        {

        }

        private void panel4_Paint(object sender, PaintEventArgs e)
        {

        }

        private void xtraTabControl1_Click(object sender, EventArgs e)
        {

        }
    }
}